### ISSUE TITLE
config/initializers/rearview.rb is missing

### ISSUE THREAD

**Issue by khash** [livingsocial/rearview#16] opened 2014-01-12 11:48 UTC
The documentation mentions this file needs to be modified before running rearview, but the file is missing from the source code.

This probably causes running <code>rake RAILS_ENV=production rearview:config:verify</code> to fail with the following reason:

<pre>
using "production" configuration:
authentication={:strategy=>:database}
default_from=rearview@localhost
default_url_options=nil
enable_alerts=true
enable_monitor=true
graphite_url=nil
logger=nil
pagerduty_url=https://events.pagerduty.com/generic/2010-04-15/create_event.json
preload_jobs=true
sandbox_dir=nil
sandbox_exec=nil
sandbox_timeout=5
verify=false
validating...rake aborted!
can't convert nil into String
org/jruby/RubyFile.java:1895:in `join'
org/jruby/RubyFile.java:826:in `join'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyKernel.java:1101:in `load'
org/jruby/RubyKernel.java:1121:in `eval'
/Users/khash/.rvm/gems/jruby-1.7.5@global/bin/jruby_executable_hooks:15:in `(root)'
Tasks: TOP => rearview:config:verify
(See full trace by running task with --trace)
D, [2014-01-12T11:52:23.061000 #44446] DEBUG -- : Shutdown completed cleanly
</pre>

**Comment by talbright** [comment] 2014-01-12 13:56
Did you run bin/setup first? Did that fail in some way? That script should copy over rearview.rb into the initializers directory. You can also copy over the configuration by running the following from the root directory:

```
bin/rails generate rearview:install
```

**Comment by talbright** [comment] 2014-01-12 14:08
closing -- this was caused by a failure in the setup script you experienced in issue #17

**Closed as completed by talbright** 2014-01-12 14:08 UTC

**Comment by ananthkollipara** [comment] 2014-04-09 07:09
Hi - same issue, i can't locate rearview.rb file. It is missing. I took code from the latest release. Below is part of the log snippet after executing "./bin/setup" file. Any advise, please?

Updating files in vendor/cache
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
Setting up sandbox...
Successfully installed bundler-1.6.1
1 gem installed
Using i18n 0.6.5
Using json 1.8.0
Using multi_json 1.8.1
Using bundler 1.6.1
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
rake aborted!
Don't know how to build task 'rearview:setup'

**Comment by talbright** [comment] 2014-04-09 12:38
Is this the full output? Are you using Jruby?

**Comment by ananthkollipara** [comment] 2014-04-09 13:02
Not the full output, last portion only. You rightly indicated, am missing jruby, apologies. Am just installing jruby, will check & update. Thank you.

**Comment by ananthkollipara** [comment] 2014-04-09 13:56
I have installed jruby...

> > > > > > jruby 1.7.11 (1.9.3p392) 2014-02-24 86339bb on OpenJDK 64-Bit Server VM 1.6.0_20-b20 [linux-amd64]
> > > > > > NameError: undefined local variable or method `rsion' for main:Object (root) at -e:1

Still same issue...

> > > > > Use `bundle show [gemname]` to see where a bundled gem is installed.
> > > > > rake aborted!
> > > > > Don't know how to build task 'rearview:setup'

(See full trace by running task with --trace)


Please advice.

**Comment by ananthkollipara** [comment] 2014-04-09 14:01
## I have also tried this...

 $bin/rails generate rearview:install
/home/kodiak/rearview/rearview-v.1.2.1/config/initializers/devise.rb:3:in `<top (required)>': uninitialized constant Devise (NameError)
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/engine.rb:609:in`block (2 levels) in class:Engine'
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/engine.rb:608:in `each'
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/engine.rb:608:in`block in class:Engine'
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/initializable.rb:30:in`run'
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/lib/ruby/2.1.0/tsort.rb:226:in`block in tsort_each'
        from /usr/local/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.1.0/tsort.rb:418:in`block (2 levels) in each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.1.0/tsort.rb:417:in`block in each_strongly_connected_component_from'
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/initializable.rb:44:in `each'
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/initializable.rb:44:in`tsort_each_child'
        from /usr/local/lib/ruby/2.1.0/tsort.rb:411:in `call'
        from /usr/local/lib/ruby/2.1.0/tsort.rb:411:in`each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.1.0/tsort.rb:345:in`each'
        from /usr/local/lib/ruby/2.1.0/tsort.rb:345:in `call'
        from /usr/local/lib/ruby/2.1.0/tsort.rb:345:in`each_strongly_connected_component'
        from /usr/local/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
        from /usr/local/lib/ruby/2.1.0/tsort.rb:205:in`tsort_each'
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/application.rb:215:in`initialize!'
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /home/kodiak/rearview/rearview-v.1.2.1/config/environment.rb:5:in`<top (required)>'
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/application.rb:189:in `require'
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/application.rb:189:in`require_environment!'
        from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.2/lib/rails/commands.rb:44:in `<top (required)>'
        from bin/rails:12:in`require'

##         from bin/rails:12:in `<main>'

**Comment by ananthkollipara** [comment] 2014-04-10 04:10
Can you please advise on this issue?

**Comment by talbright** [comment] 2014-04-10 14:06
Do the following and paste all the output in your response:

```
$ which ruby
$ ruby -v
$ java -version
$ which gem
$ gem install bundler --no-rdoc --no-ri
$ which bundle
$ bundle install
```

**Comment by ananthkollipara** [comment] 2014-04-10 14:11
Trent, I could figure out the issue & resolved to greater extent. Am currently stuck in bringing up mySQL. The only issue now is with "Unknown database 'rearview_production'"

## Please see below.

[root@kodiak-SA2 rearview-1.2.0]# foreman start
file:/usr/local/rvm/rubies/jruby-1.7.5/lib/jruby.jar!/jruby/kernel19/process.rb:14 warning: unsupported spawn option: err
file:/usr/local/rvm/rubies/jruby-1.7.5/lib/jruby.jar!/jruby/kernel19/process.rb:14 warning: unsupported spawn option: out
19:37:04 web.1  | started with pid 25107
=> Booting Puma
=> Rails 4.0.2 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server

---

{:adapter=>"mysql", :database=>"rearview_production", :username=>"root", :password=>nil, :host=>"localhost"}

---

---

active_record/connection_adapters/mysql_adapter

---

Exiting
ActiveRecord::JDBCError: The driver encountered an unknown error: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'rearview_production'

**Comment by talbright** [comment] 2014-04-10 14:14
Tell me the output of this:

```
$ bundle exec rake RAILS_ENV=production rearview:setup
```

**Comment by ananthkollipara** [comment] 2014-04-10 14:20
Looks like this works !!! I think, i should point graphite URL. Anything else to get going?

[root@kodiak-SA2 rearview-1.2.0]# bundle exec rake RAILS_ENV=production rearview:setup

---

{:adapter=>"mysql", :database=>"rearview_production", :username=>"root", :password=>nil, :host=>"localhost"}

---

---

active_record/connection_adapters/mysql_adapter

---

---

{:adapter=>"mysql", :database=>nil, :username=>"root", :password=>nil, :host=>"localhost"}

---

---

active_record/connection_adapters/mysql_adapter

---

---

{:adapter=>"mysql", :database=>"rearview_production", :username=>"root", :password=>nil, :host=>"localhost"}

---

---

active_record/connection_adapters/mysql_adapter

---

---

{:adapter=>"mysql", :database=>"rearview_production", :username=>"root", :password=>nil, :host=>"localhost"}

---

---

active_record/connection_adapters/mysql_adapter

---

==  BaseSchema: migrating =====================================================
-- create_table("applications", {:force=>true})
   -> 0.1010s
-- add_index("applications", ["ancestry"], {:name=>"index_applications_on_ancestry"})
   -> 0.1640s
   -> 0 rows
-- add_index("applications", ["user_id"], {:name=>"user_id"})
   -> 0.1680s
   -> 0 rows
-- create_table("job_data", {:force=>true})
   -> 0.0920s
-- create_table("job_errors", {:force=>true})
   -> 0.0810s
-- add_index("job_errors", ["job_id"], {:name=>"job_id"})
   -> 0.1680s
   -> 0 rows
-- create_table("jobs", {:force=>true})
   -> 0.1160s
-- add_index("jobs", ["app_id"], {:name=>"app_id"})
   -> 0.1690s
   -> 0 rows
-- add_index("jobs", ["id", "name"], {:name=>"id_name_version_key", :unique=>true})
   -> 0.1830s
   -> 0 rows
-- add_index("jobs", ["user_id"], {:name=>"jobs_ibfk_1"})
   -> 0.1830s
   -> 0 rows
-- create_table("users", {:force=>true})
   -> 0.1040s
-- add_index("users", ["email"], {:name=>"email", :unique=>true})
   -> 0.1720s
   -> 0 rows
==  BaseSchema: migrated (1.7070s) ============================================

==  AddIndexes: migrating =====================================================
-- add_index(:jobs, :status)
   -> 0.1740s
   -> 0 rows
-- add_index(:job_errors, :status)
   -> 0.1760s
   -> 0 rows
-- add_index(:job_data, :job_id)
   -> 0.1830s
   -> 0 rows
==  AddIndexes: migrated (0.5350s) ============================================

---

{:adapter=>"mysql", :database=>"rearview_production", :username=>"root", :password=>nil, :host=>"localhost"}

---

---

active_record/connection_adapters/mysql_adapter

---

```
conflict  config/initializers/rearview.rb
```

Overwrite /home/kodiak/rearview-1.2.0/config/initializers/rearview.rb? (enter "h" for help) [Ynaqdh] Y

#        force  config/initializers/rearview.rb

Before running rearview you must specify a few settings manually.

Edit the following file:

```
config/initializers/rearview.rb
```

You must set **config.graphite_url** and **config.sandbox_exec** for rearview
to run properly. Most of the other settings you should be able to leave as is.

# 

setup done

**Comment by ananthkollipara** [comment] 2014-04-10 14:34
thanks a ton, i could bring up. Will check, if i have any other issue.

```
[root@kodiak-SA2 rearview-1.2.0]# foreman start
file:/usr/local/rvm/rubies/jruby-1.7.5/lib/jruby.jar!/jruby/kernel19/process.rb:14 warning: unsupported spawn option: err
file:/usr/local/rvm/rubies/jruby-1.7.5/lib/jruby.jar!/jruby/kernel19/process.rb:14 warning: unsupported spawn option: out
19:58:21 web.1  | started with pid 25494
=> Booting Puma
=> Rails 4.0.2 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
********************************************************************************
{:adapter=>"mysql", :database=>"rearview_production", :username=>"root", :password=>nil, :host=>"localhost"}
********
********************************************************************************
active_record/connection_adapters/mysql_adapter
********
Puma 2.7.1 starting...
* Min threads: 0, max threads: 16
* Environment: production
* Listening on tcp://0.0.0.0:3000
```
